revert to python2.7
The bundled charm-helpers doesn't support Python 3, but even
when it's updated it reveals that the core code needs work too,
e.g. ensure_package_status:

  File "/var/lib/juju/agents/unit-apache2-0/charm/hooks/upgrade-charm", line 70, in ensure_package_status
    dpkg.communicate(input=selections)
  File "/usr/lib/python3.6/subprocess.py", line 848, in communicate
    self._stdin_write(input)
  File "/usr/lib/python3.6/subprocess.py", line 801, in _stdin_write
    self.stdin.write(input)
TypeError: a bytes-like object is required, not 'str'